name: Robot Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          pip install -r requirements.txt
          rfbrowser init
      - name: Run Robot (demo by default)
        env:
          PROFILE: demo
          HEADLESS: "true"
        run: |
          robot -v PROFILE:${PROFILE} -v HEADLESS:${HEADLESS} tests
      - name: Upload Robot Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: robot-logs
          path: |
            log.html
            report.html
            output.xml
